apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: deployment-demo
spec:
  ports:
  - nodePort: 30500 #k8s node with this port allows to access to this svc
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort